# Generated by Django 3.2 on 2021-05-08 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0002_rename_name_dailymenu_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='menu1',
            field=models.CharField(blank=True, choices=[('', (('', '-----'),)), ('Debt', (('m11', 'Credit Card'), ('m12', 'Student Loans'), ('m13', 'Taxes'))), ('Entertainment', (('21', 'Books'), ('22', 'Games'))), ('Everyday', (('31', 'Groceries'), ('32', 'Restaurants')))], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='menu2',
            field=models.CharField(blank=True, choices=[('', (('', '-----'),)), ('Debt', (('m11', 'Credit Card'), ('m12', 'Student Loans'), ('m13', 'Taxes'))), ('Entertainment', (('21', 'Books'), ('22', 'Games'))), ('Everyday', (('31', 'Groceries'), ('32', 'Restaurants')))], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='menu3',
            field=models.CharField(blank=True, choices=[('', (('', '-----'),)), ('Debt', (('m11', 'Credit Card'), ('m12', 'Student Loans'), ('m13', 'Taxes'))), ('Entertainment', (('21', 'Books'), ('22', 'Games'))), ('Everyday', (('31', 'Groceries'), ('32', 'Restaurants')))], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu1', models.CharField(choices=[('', (('', '-----'),)), ('Debt', (('m11', 'Credit Card'), ('m12', 'Student Loans'), ('m13', 'Taxes'))), ('Entertainment', (('21', 'Books'), ('22', 'Games'))), ('Everyday', (('31', 'Groceries'), ('32', 'Restaurants')))], max_length=100)),
                ('menu2', models.CharField(choices=[('', (('', '-----'),)), ('Debt', (('m11', 'Credit Card'), ('m12', 'Student Loans'), ('m13', 'Taxes'))), ('Entertainment', (('21', 'Books'), ('22', 'Games'))), ('Everyday', (('31', 'Groceries'), ('32', 'Restaurants')))], max_length=100)),
                ('menu3', models.CharField(blank=True, choices=[('', (('', '-----'),)), ('Debt', (('m11', 'Credit Card'), ('m12', 'Student Loans'), ('m13', 'Taxes'))), ('Entertainment', (('21', 'Books'), ('22', 'Games'))), ('Everyday', (('31', 'Groceries'), ('32', 'Restaurants')))], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
